version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: mercury-postgres
    environment:
      POSTGRES_PASSWORD: "postpass"
      POSTGRES_USER: postuser
      POSTGRES_DB: mercury
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/postgres/init:/docker-entrypoint-initdb.d:ro
    networks:
      - mercury-net

  redis:
    image: redis:7.2
    container_name: mercury-redis
    ports:
      - "6379:6379"
    networks:
      - mercury-net
    volumes:
      - redisdata:/data

  kafka:
    image: apache/kafka:3.8.0
    container_name: mercury-kafka
    ports:
      - "9092:9092" #clients on host
      - "9093:9093" #controller
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"

      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_NUM_PARTITIONS: "3"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"

    networks:
      - mercury-net
    volumes:
      - kafkadata:/var/lib/kafka/data

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.97.0
    container_name: mercury-otel-collector
    restart: unless-stopped
    command: ["--config=/etc/otelcol/config.yml"]
    volumes:
      - ./infra/otel/collector-config.yml:/etc/otelcol/config.yml:ro
    ports:
      - "4317:4317" # apps -> collector (OTLP gRPC)
      - "4318:4318" # apps -> collector (OTLP HTTP)
      - "8889:8889" # prometheus scrape endpoint (collector exporter)
    networks: [mercury-net]

  jaeger:
    image: jaegertracing/all-in-one:1.54
    container_name: mercury-jaeger
    restart: unless-stopped
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686" # UI
    networks: [mercury-net]

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: mercury-prometheus
    restart: unless-stopped
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks: [mercury-net]

  grafana:
    image: grafana/grafana:11.0.0
    container_name: mercury-grafana
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"

    volumes:
      - grafana-data:/var/lib/grafana
      - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro

    networks:
      - mercury-net

  loki:
    image: grafana/loki:2.9.6
    container_name: mercury-loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks: [mercury-net]

  promtail:
    image: grafana/promtail:2.9.6
    container_name: mercury-promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./infra/promtail/promtail.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    networks: [mercury-net]

  mercury-catalog-service:
    image: mercury-catalog-service:latest
    container_name: mercury-catalog-service
    ports:
      - "8080:8080"
    networks:
      - mercury-net
    environment:
      # If you later add OTEL metrics/traces export:
      JAVA_TOOL_OPTIONS: "-javaagent:/otel/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: "mercury-catalog-service"
      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
      OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
      OTEL_LOG_LEVEL: "info"
      OTEL_LOGS_EXPORTER: none
      OTEL_METRICS_EXPORTER: none
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - "$PWD/infra/otel/opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar:ro"

  mercury-order-service:
    image: mercury-order-service:latest
    container_name: mercury-order-service
    ports:
      - "8081:8080"
    networks:
      - mercury-net
    environment:
      # If you later add OTEL metrics/traces export:
      JAVA_TOOL_OPTIONS: "-javaagent:/otel/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: "mercury-order-service"
      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
      OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
      OTEL_LOG_LEVEL: "info"
      OTEL_LOGS_EXPORTER: none
      OTEL_METRICS_EXPORTER: none
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - "$PWD/infra/otel/opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar:ro"

volumes:
  pgdata:
  redisdata:
  kafkadata:
  grafana-data:

networks:
  mercury-net:
    name: mercury-net
    driver: bridge
