worker_processes 1;

#how nginx talks the kernel. defines how nginx workers sleep, wake and accept sockers from the kernel
events { worker_connections 1024; }

http {

    upstream catalog{
        server mercury-catalog-service:8080;
    }

    upstream orders{
        server mercury-order-service:8080;
    }

    server {
        listen 80;
        server_name localhost;

        #these can be shared or passed individually in location contexts
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        location /catalog/{
            proxy_pass http://catalog/;

            proxy_connect_timeout 1s; #time to establish TCP to upstream (or TLS handshake if HTTPS upstream).
            proxy_send_timeout 7s; #ime allowed for Nginx to send the request to the upstream (relevant if upstream is slow to read / backpressured)
            proxy_read_timeout 7s; #time Nginx waits between reads from upstream response (this is the usual “upstream took too long” timeout).

            # proxy_set_header Host $host;
            # proxy_set_header X-Real-IP $remote_addr;
            # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # proxy_set_header X-Forwarded-Proto $scheme;
        }

        location = /catalog {
            return 301 /catalog/;
        }

        location /orders/ {
            proxy_pass http://orders/;

            proxy_connect_timeout 3s;
            proxy_send_timeout 8s;
            proxy_read_timeout 10s;

            # proxy_set_header Host $host;
            # proxy_set_header X-Real-IP $remote_addr;
            # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # proxy_set_header X-Forwarded-Proto $scheme;
        }

        location = /orders {
            return 301 /orders/;
        }

        location / {
            return 404 "Use /catalog/* or /orders/*";
        }
    }
}